name: sentiment_avatar
on:
  push: 
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    environment: tw
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v2
      with:
        path: "requirements.txt"
    - name: execute py script # run the run.py to get the latest data
      run: |
        python avatar.py
      env:
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        TB_TOKEN: ${{ secrets.TB_TOKEN }}
        READ_TOKEN: ${{ secrets.READ_TOKEN }}